# Generated by Django 2.0.3 on 2018-03-13 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=0, max_digits=1)),
                ('prep_time', models.CharField(max_length=30)),
                ('cooking_time', models.CharField(max_length=30)),
                ('servings', models.DecimalField(decimal_places=0, max_digits=2)),
                ('ingredients', models.TextField()),
                ('cooking_instructions', models.TextField()),
            ],
        ),
    ]
